### PR TITLE
chore: pack index.mjs

### PR DESCRIPTION
**Pull request by davidfragalaureano**
Requested here: https://exodusio.slack.com/archives/CP202D90Q/p1717022376889879

### CODE REVIEW

**Comment by davidfragalaureano** [comment]
tACK

image

**Comment by ChALkeR** [comment]
This misses a release

Alternatively this could have just removed `"module": "./dist/index.mjs",` from `package.json`, that's why it was breaking

**Comment by davidfragalaureano** [comment]
@ChALkeR Do you need the release urgently?
I can do it in a bit, AFK rn.

Or going for your suggestion might be better?

**Comment by ChALkeR** [comment]
Upd: also remove in addition to removing `"module": "./dist/index.mjs"`:
```
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js",
      "types": "./dist/index.d.ts"
    }
  },
  ```

@davidfragalaureano re:release - no idea, cc @fboucquez

**Comment by fboucquez** [comment]
Thanks @davidfragalaureano for releasing, this will unblock Lanre

**Pull request merged**
